protected/modules/admin/models/Goals.php
<?php

	/**
	 * This is the model class for table "goals".
	 *
	 * The followings are the available columns in table 'goals':
	 *
	 * @property integer  $id
	 * @property integer  $contact_id
	 * @property integer  $status_ma
	 * @property string   $name
	 * @property integer  $year
	 * @property string   $start_date
	 * @property string   $end_date
	 * @property integer  $average_sales_price
	 * @property integer  $lead_gen_min_per_day
	 * @property integer  $income_per_year
     * @property integer  $fees
	 * @property integer  $average_commission_percent
	 * @property string   $contracts_closing_conversion
	 * @property string   $agreements_contract_conversion
	 * @property string   $appointments_agreement_conversion
     * @property string   $appointments_set_met_conversion
	 * @property integer  $contacts_per_appointment
     * @property integer  $contacts_per_hour
	 * @property integer  $contacts_per_day
	 * @property string   $referral_percentage
	 * @property integer  $is_deleted
	 *
	 * The followings are the available model relations:
	 * @property Contacts $contact
	 */
	class Goals extends StmBaseActiveRecord {

		/**
		 * Returns the static model of the specified AR class.
		 *
		 * @param string $className active record class name.
		 *
		 * @return Goals the static model class
		 */
		public static function model($className = __CLASS__) {
			return parent::model($className);
		}

		/**
		 * @return string the associated database table name
		 */
		public function tableName() {
			return 'goals';
		}

		/**
		 * @return array validation rules for model attributes.
		 */
		public function rules() {
			// NOTE: you should only define rules for those attributes that
			// will receive user inputs.
			return array(
				array(
					'contact_id, status_ma, name, year, start_date, end_date, average_sales_price, lead_gen_minutes_per_day, income_per_year, average_commission_percent, commission_split, contracts_closing_conversion, agreements_contract_conversion, appointments_agreement_conversion, appointments_set_met_conversion, contacts_per_appointment, contacts_per_hour, contacts_per_day',
					'required'
				),
				array(
					'contact_id, status_ma, year, average_sales_price, lead_gen_minutes_per_day, weeks_time_off, income_per_year, fees, contacts_per_appointment, contacts_per_hour, contacts_per_day, is_deleted',
					'numerical',
					'integerOnly' => true
				),
                array(
                    'year_id',
                    'validateYear'
                ),
				array(
					'name',
					'length',
					'max' => 63
				),
				array(
					'contracts_closing_conversion, agreements_contract_conversion, appointments_agreement_conversion, referral_percentage',
					'length',
					'max' => 5
				),
                array(
                    'start_date',
                    'validateStartEndDate'
                ),
				array(
					'start_date, end_date, commission_split',
					'safe'
				),
				// The following rule is used by search().
				// Please remove those attributes that should not be searched.
				array(
					'id, contact_id, status_ma, name, year, start_date, end_date, average_sales_price, lead_gen_minutes_per_day, weeks_time_off, income_per_year, fees, average_commission_percent, commission_split, contracts_closing_conversion, agreements_contract_conversion, appointments_agreement_conversion, appointments_set_met_conversion, contacts_per_appointment, contacts_per_hour, contacts_per_day, referral_percentage, is_deleted',
					'safe',
					'on' => 'search'
				),
			);
		}

		/**
		 * @return array relational rules.
		 */
		public function relations() {
			// NOTE: you may need to adjust the relation name and the related
			// class name for the relations automatically generated below.
			return array(
                'contact' => array(self::BELONGS_TO, 'Contacts', 'contact_id'),
                'weeklyGoals' => array(self::HAS_MANY, 'GoalsWeekly', 'goal_id'),
			);
		}

		/**
		 * @return array customized attribute labels (name=>label)
		 */
		public function attributeLabels() {
			return array(
				'id' => 'ID',
				'contact_id' => 'Contact',
				'status_ma' => 'Status Ma',
				'name' => 'Goal Name',
				'year' => 'Year',
				'start_date' => 'Start Date',
				'end_date' => 'End Date',
				'average_sales_price' => 'Average Sales Price',
				'average_commission_percent' => 'Avg Gross Commission %',
				'commission_split' => 'Commission Split',
				'lead_gen_minutes_per_day' => 'Daily Lead Gen Minutes',
				'weeks_time_off' => 'Weeks Time Off',
				'income_per_year' => 'Annual Income',
                'fees' => 'Fees',
				'contracts_closing_conversion' => 'Contracts-to-Closing',
				'agreements_contract_conversion' => 'Agreements-to-Contract',
				'appointments_agreement_conversion' => 'Appts-to-Agreement',
				'contacts_per_appointment' => 'Contacts Per Appt',
                'contacts_per_hour' => 'Contacts Per Hour',
				'contacts_per_day' => 'Contacts Per Day',
				// leave in for now...
				'referral_percentage' => 'Referral Percentage',
				'is_deleted' => 'Is Deleted',
				'incomePerClosing' => 'Income per Closing',
			);
		}

		public function getMonthlyContacts() {
			if (isset($this->contacts_per_day)) {
				return $this->contacts_per_day * 20;
			} else {
				return 0;
			}
		}

		public function getIncomePerClosing() {
			if (!empty($this->average_sales_price) && !empty($this->average_commission_percent) && !empty($this->commission_split)) {
				return ceil($this->average_sales_price * $this->average_commission_percent * $this->commission_split
				);
			} else {
				return 0;
			}
		}

		public function getMonthlyLeadGen() {
			return ceil($this->lead_gen_minutes_per_day * 16 / 60);
		}

		public function getMonthlyAppointments() {
			return ceil($this->annualAppointments / 12);
		}

		public function getMonthlyAgreements() {
			return ceil($this->annualAgreements / 12);
		}

		public function getMonthlyContracts() {
			return ceil($this->annualContracts / 12);
		}

		public function getMonthlyClosings() {
			return ceil($this->annualClosings / 12);
		}

		public function getMonthlyIncome() {
			return ceil($this->income_per_year / 12);
		}

		public function getAnnualClosings() {
			if (isset($this->income_per_year) && !empty($this->income_per_year) && $this->incomePerClosing) {
				return ceil($this->income_per_year / $this->incomePerClosing);
			} else {
				return 0;
			}
		}

		public function getAnnualContracts() {
			if (isset($this->annualClosings) && $this->annualClosings && !empty($this->contracts_closing_conversion)) {
				return ceil($this->annualClosings / $this->contracts_closing_conversion);
			} else {
				return 0;
			}
		}

		public function getAnnualAgreements() {
			if (isset($this->annualContracts) && $this->annualContracts && !empty($this->agreements_contract_conversion)) {
				return ceil($this->annualContracts / $this->agreements_contract_conversion
				);
			} else {
				return 0;
			}
		}

		public function getAnnualAppointments() {
			if (isset($this->annualAgreements) && $this->annualAgreements && !empty($this->appointments_agreement_conversion)) {
				return ceil($this->annualAgreements / $this->appointments_agreement_conversion
				);
			} else {
				return 0;
			}
		}

		public function getAnnualContacts() {
			return ceil($this->annualAppointments * $this->contacts_per_appointment);
		}

		public function getWeeklyContacts() {
			return ceil($this->annualContacts / (52 - $this->weeks_time_off));
		}

		public function getDailyContacts() {
			return ceil($this->getWeeklyContacts() / 4);
		}

        public function getAnnualLeadGen() {
            return ceil($this->lead_gen_minutes_per_day / 60 * 5 * (52 - $this->weeks_time_off));
        }

        public function getActualLeadGen($opts = null) {
			$opts['default_preset'] = 'this_month';
			$opts = Yii::app()->format->formatDateRangeArray($opts);

			$actualLeadGen = 0;
			$Timeblock = Timeblockings::model()->byCurrentUser()->dateRange($opts)->byTypes(Timeblockings::LEAD_GEN_TYPE_PHONE_ID)->calculateMinutes()->find();

			return number_format($Timeblock->minutes);
		}

		public function getDueLeadGen() {
			return number_format($this->monthlyLeadGen * $this->percent);
		}

		public function getActualDials() {
			$opts['default_preset'] = 'this_month';
			$opts = Yii::app()->format->formatDateRangeArray($opts);

			return ActivityLog::countLeadGenDials($opts);
		}

		public function getDueDials() {
			return number_format($this->dueContacts * 3);
		}

		public function getActualContacts($opts = null) {
			$opts['default_preset'] = 'this_month';
			$opts = Yii::app()->format->formatDateRangeArray($opts);

			return ActivityLog::countLeadGenContacts($opts);
		}

		public function getDueContacts() {
			return number_format($this->monthlyContacts * $this->percent);
		}

		public function getActualAppts() {
			$opts['default_preset'] = 'this_month';
			$opts = Yii::app()->format->formatDateRangeArray($opts);

			return Appointments::countMetAppointments($opts);
		}

		public function getDueAppts() {
			return number_format($this->monthlyAppointments * $this->percent);
		}

		public function getActualSigned() {
			$opts['default_preset'] = 'this_month';
			$opts = Yii::app()->format->formatDateRangeArray($opts);

			return Appointments::countSignedAppointments($opts);
		}

		public function getDueSigned() {
			return number_format($this->monthlyAgreements * $this->percent);
		}

		public function getActualContracts() {
			$opts['default_preset'] = 'this_month';
			$opts = Yii::app()->format->formatDateRangeArray($opts);
			$opts['contactId'] = Yii::app()->user->id;

			return Closings::getCountExecutedByAssigneeId($opts);
		}

		public function getDueContracts() {
			return number_format($this->monthlyContracts * $this->percent);
		}

		public function getActualClosings() {
			$opts['default_preset'] = 'this_month';
			$opts = Yii::app()->format->formatDateRangeArray($opts);

protected/modules/admin/controllers/GoalsController.php
<?php
class GoalsController extends AdminController
{
	public $pageColor = 'blue';
    /**
     * Specifies the action rules.
     * @return array actions
     */
    public function actions()
    {
        return array(
			'index'       =>'stm_app.modules.admin.controllers.actions.goals.ListAction',
            'list'        =>'stm_app.modules.admin.controllers.actions.goals.ListAction',
            'add'         =>'stm_app.modules.admin.controllers.actions.goals.AddAction',
			'addOneThing' =>'stm_app.modules.admin.controllers.actions.goals.AddOneThingAction',
            'addWeekly'  =>'stm_app.modules.admin.controllers.actions.goals.AddWeeklyAction',
			// 'data'     =>'stm_app.modules.admin.controllers.actions.goals.DataAction',
			'edit'        =>'stm_app.modules.admin.controllers.actions.goals.EditAction',
            'editOneThing' =>'stm_app.modules.admin.controllers.actions.goals.EditOneThingAction',
            'editWeekly'  =>'stm_app.modules.admin.controllers.actions.goals.EditWeeklyAction',
			'dashboard'   =>'stm_app.modules.admin.controllers.actions.goals.DashboardAction',
			// 'view'     =>'stm_app.modules.admin.controllers.actions.goals.ViewAction',
            'calculator'  =>'stm_app.modules.admin.controllers.actions.goals.CalculatorAction',
            'oneThing'    =>'stm_app.modules.admin.controllers.actions.goals.OneThingAction',
        );
    }

	/**
	 * @return array action filters
	 */
	public function filters() {
		return CMap::mergeArray(parent::filters(), array(

		));
	}

// appts-set-met
    /**
     * Initializes the controller
     * @return none
     */
    public function init() {
        $this->displayName = 'Goals';
        $this->baseModel = new Goals;
    }

    public function zeroClass($model, $attribute)
    {
        if($model->{$attribute} == 0) {
            return ' zero';
        }
    }
}

protected/modules/admin/views/goals/_dashboard.php
<h1 class="p-pt10">Goals</h1>

<h3>Annaul Goals</h3>
Income: $100,000<br/>
# Closings: 34<br/>
# Contracts: 40<br/>
# Agreements: 48<br/>
# Appointments: 54<br/>
# Contacts per Appt: 15<br/>

protected/modules/admin/views/goals/_form.php
<?php $this->widget('admin_module.extensions.moneymask.MMask',array(
    'element'=>'#Goals_average_sales_price, #Goals_income_per_closing, #Goals_income_per_year, #Goals_fees',
    'currency'=>'PHP',
    'config'=>array(
    	'precision'=>0,
    	'symbol'=>'$',
    	'showSymbol'=>true,
    )
));

$this->widget('admin_module.extensions.moneymask.MMask',array(
    'element'=>'#Goals_contacts_per_appointment, #Goals_lead_gen_minutes_per_day, #Goals_contacts_per_day',
    'currency'=>'PHP',
    'config'=>array(
    	'precision'=>0,
    	'thousands'=>'',
    )
));

$form=$this->beginWidget('CActiveForm', array(
	'id'=>'goals-form',
	'enableAjaxValidation'=>false,
));
	$this->beginStmPortletContent(array(
		'handleTitle'=>$mode.' Goals',
		'handleIconCss'=>'i_wizard'
	));
	?>
	<div id="goals-container" >
		<div class="g12 p-mb5 rounded-text-box odd-static">
			<div id="goals-left" class="g6">
		        <table class="container">
		        	<tr>
		        		<th><?php echo $form->labelEx($model, 'status_ma');?></th>
		        		<td><?php echo $form->dropDownList($model, 'status_ma', array(1=>'Active', 0=>'Inactive'), $htmlOptions=array('empty'=>'Select One')); ?>
		        			<?php echo $form->error($model,'status_ma'); ?>
		        		</td>
		        	</tr>
		        	<tr>
		        		<th><?php echo $form->labelEx($model, 'name');?></th>
		        		<td><?php echo $form->textField($model,'name', $htmlOptions=array('placeholder'=>'Goal Name', 'class'=>'g9', ));?>
		        			<?php echo $form->error($model,'name'); ?>
		        		</td>
		        	</tr>
		        </table>
	    	</div>
			<div id="goals-right" class="g6">
		        <table class="container">
		        	<tr>
		        		<th><?php echo $form->labelEx($model, 'year');?></th>
		        		<td><?php $startYear = ($model->year> 2000)? $model->year : date('Y');
                            $yearData = StmFormHelper::getDropDownList($opt=array('start'=>$startYear,'end'=>date('Y')+1,'increment'=>1));
                            echo $form->dropDownList($model, 'year', $yearData,
		        									$htmlOptions=array('empty'=>'Select One','class'=>'g4'));
		        			?>
		        			<?php echo $form->error($model,'year'); ?>
		        		</td>
		        	</tr>
		        	<tr>
		        		<th>Date Range</th>
		        		<td>
                            <div class="g5">
                                <?	$this->widget('zii.widgets.jui.CJuiDatePicker', array(
                                        'model'=>$model,
                                        'attribute'=>'start_date',
                                        'options'=>array(
                                            'showAnim'=>'fold',
                                        ),
                                        'htmlOptions'=>array(
                                            'placeholder'=>'Start Date',
                                            'class'=>'g100',
                                            'readonly'=>'readonly',
                                        ),
                                    ));
                                ?>
                                <?php echo $form->error($model,'start_date',$htmlOptions=array('style'=>'display:inline-block;')); ?>
                            </div>
							<span class="label p-p9"> to </span>
                            <div class="g5">
                                <?	$this->widget('zii.widgets.jui.CJuiDatePicker', array(
                                        'model'=>$model,
                                        'attribute'=>'end_date',
                                        'options'=>array(
                                            'showAnim'=>'fold',
                                        ),
                                        'htmlOptions'=>array(
                                            'placeholder'=>'End Date',
                                            'class'=>'g100',
                                            'readonly'=>'readonly',
                                        ),
                                    ));
                                ?>
                                <?php echo $form->error($model,'end_date',$htmlOptions=array('style'=>'display:inline-block; margin-left:5px;')); ?>
                            </div>
		        		</td>
		        	</tr>
		        </table>
	    	</div>

	    	<hr />

	        <table class="container">
	        	<tr>
	        		<th class="narrow"><?php echo $form->labelEx($model, 'income_per_year');?></th>
	        		<td>
                        <?php echo $form->textField($model,'income_per_year', $htmlOptions=array('placeholder'=>'Annual Income', 'class'=>'g3 income-goal', ));?>
                        <div class="g3"></div>
                        <div class="g4" style="display: block; background: #f5f63a; padding:6px; text-align: center; font-size: 16px; border-radius: 4px; -webkit-border-radius: 4px; -moz-border-radius: 4px;">Note: To Update Calculations<br />Click Submit Below.</div>
	        			<?php echo $form->error($model,'income_per_year'); ?>
	        		</td>
	        	</tr>
                <tr>
                    <th class="narrow"><?php echo $form->labelEx($model, 'fees');?></th>
                    <td>
                        <?php echo $form->textField($model,'fees', $htmlOptions=array('placeholder'=>'Fees', 'class'=>'g3', ));?>
                        <div class="g3"></div>
                        <div class="g4" style="display: block; background: #f5f63a; padding:6px; text-align: center; font-size: 16px; border-radius: 4px; -webkit-border-radius: 4px; -moz-border-radius: 4px;">Note: To Update Calculations<br />Click Submit Below.</div>
                        <?php echo $form->error($model,'fees'); ?>
                    </td>
                </tr>
	        </table>
			<div id="goals-left" class="g6">
		        <table class="container">
		        	<tr>
		        		<th><?php echo $form->labelEx($model, 'average_sales_price');?></th>
		        		<td><?php echo $form->textField($model,'average_sales_price', $htmlOptions=array('placeholder'=>'Average Sales Price', 'class'=>'g4', ));?>
		        			<?php echo $form->error($model,'average_sales_price'); ?>
		        		</td>
		        	</tr>
		        	<tr>
		        		<th><?php echo $form->labelEx($model, 'incomePerClosing');?></th>
		        		<td>
		        			<label class="goals-metric p-mr5"><?php echo '$'.number_format($model->incomePerClosing);?></label>
		        		</td>
		        	</tr>
		        	<tr>
		        		<th><?php echo $form->labelEx($model, 'average_commission_percent');?></th>
		        		<td><?php echo $form->dropDownList($model, 'average_commission_percent', StmFormHelper::getPercentageList(array('max'=>10,'sort'=>'asc')), $htmlOptions=array('empty'=>'Select One', 'class'=>'g3',)); ?>
		        			<?php echo $form->error($model,'average_commission_percent'); ?>
		        		</td>
		        	</tr>
		        	<tr>
		        		<th><?php echo $form->labelEx($model, 'commission_split');?></th>
		        		<td>
                            <?php echo $form->dropDownList($model, 'commission_split', StmFormHelper::getPercentageList(array('sort'=>'asc')), $htmlOptions=array('empty'=>'Select One', 'class'=>'g3',)); ?>
		        			<?php echo $form->error($model,'commission_split'); ?>
		        		</td>
		        	</tr>
		        	<tr>
		        		<th>Closings per Year</th>
		        		<td><label class="goals-metric p-mr5"><?php echo $model->annualClosings;?></label>
		        		</td>
		        	</tr>

		        </table>
	    	</div>
			<div id="goals-right" class="g6">
		        <table class="container">
		        	<tr>
		        		<th><?php echo $form->labelEx($model, 'contracts_closing_conversion');?></th>
		        		<td><?php echo $form->dropDownList($model, 'contracts_closing_conversion', StmFormHelper::getPercentageList(), $htmlOptions=array('empty'=>'Select One', 'class'=>'g3',)); ?><span class="label p-p9">=</span><label class="goals-metric p-mr5"><?php echo $model->annualContracts;?></label><span class="label p-pt8">Contracts per Year</span>
		        			<?php echo $form->error($model,'contracts_closing_conversion'); ?>
		        		</td>
		        	</tr>
		        	<tr>
		        		<th><?php echo $form->labelEx($model, 'agreements_contract_conversion');?></th>
		        		<td><?php echo $form->dropDownList($model, 'agreements_contract_conversion', StmFormHelper::getPercentageList(), $htmlOptions=array('empty'=>'Select One', 'class'=>'g3',)); ?><span class="label p-p9">=</span><label class="goals-metric p-mr5"><?php echo $model->annualAgreements;?></label><span class="label p-pt8">Agreements per Year</span>
		        			<?php echo $form->error($model,'agreements_contract_conversion'); ?>
		        		</td>
		        	</tr>
		        	<tr>
		        		<th><?php echo $form->labelEx($model, 'appointments_agreement_conversion');?></th>
		        		<td><?php echo $form->dropDownList($model, 'appointments_agreement_conversion', StmFormHelper::getPercentageList(), $htmlOptions=array('empty'=>'Select One', 'class'=>'g3',)); ?><span class="label p-p9">=</span><label class="goals-metric p-mr5"><?php echo $model->annualAppointments;?></label><span class="label p-pt8">Appts Met per Year</span>
		        			<?php echo $form->error($model,'appointments_agreement_conversion'); ?>
		        		</td>
		        	</tr>
                    <tr>
                        <th><?php echo $form->labelEx($model, 'appointments_set_met_conversion');?></th>
                        <td><?php echo $form->dropDownList($model, 'appointments_set_met_conversion', StmFormHelper::getPercentageList(), $htmlOptions=array('empty'=>'Select One', 'class'=>'g3',)); ?><span class="label p-p9">=</span><label class="goals-metric p-mr5"><?php echo ($model->appointments_set_met_conversion > 0)? round($model->annualAppointments/$model->appointments_set_met_conversion) : '-';?></label><span class="label p-pt8">Appts Set per Year</span>
                            <?php echo $form->error($model,'appointments_set_met_conversion'); ?>
                        </td>
                    </tr>
		        	<tr>
		        		<th><?php echo $form->labelEx($model, 'contacts_per_appointment');?></th>
		        		<td>
                            <?php echo $form->dropDownList($model, 'contacts_per_appointment', StmFormHelper::getDropDownList(array('start'=>1,'end'=>100,'increment'=>1)), $htmlOptions=array('empty'=>'Select One', 'class'=>'g3',)); ?><span class="label p-p9">=</span><label class="goals-metric p-mr5"><?php echo $model->annualContacts;?></label><span class="label p-pt8">Contacts per Year</span>
		        			<?php echo $form->error($model,'contacts_per_appointment'); ?>
		        		</td>
		        	</tr>
		        	<tr>
		        		<th><label>Contacts per Month</label></th>
		        		<td><label class="goals-metric p-mr5"><?php echo ceil($model->annualContacts/10.5);?></label><span class="label p-p9">=</span><label class="goals-metric p-mr5"><?php echo $model->weeklyContacts;?></label><span class="label p-p9">Contacts per Week</span>
		        		</td>
		        	</tr>
                    <tr>
                        <th><label>Weeks Without Lead Gen</label></th>
                        <td>
                            <?php echo $form->dropDownList($model, 'weeks_time_off', StmFormHelper::getDropDownList(array('start'=>1,'end'=>52,'increment'=>1)), $htmlOptions=array('empty'=>'Select One', 'class'=>'g3',)); ?>
                            <span class="label"><u>9 weeks suggested</u><br>
                                3 weeks: Vacation<br>
                                2 weeks: Christmas / Thanksgiving<br>
                                2 weeks: Education / Training<br>
                                1 weeks: Other Holidays<br>
                                1 weeks: Sick/Personal/Misc<br>
                            </span>
                        </td>
                    </tr>
		        	<tr>
		        		<th><label>Contacts per Day</label></th>
		        		<td>
                            <label class="goals-metric p-mr5"><?php echo ceil($model->contacts_per_day);?></label><span class="label p-p9">@ 4 lead gen days per week</span>
		        		</td>
		        	</tr>
		        	<tr>
		        		<th><?php echo $form->labelEx($model, 'lead_gen_minutes_per_day');?></th>
		        		<td>
                            <?php echo $form->dropDownList($model, 'lead_gen_minutes_per_day', StmFormHelper::getDropDownList(array('start'=>1,'end'=>480,'increment'=>1)), $htmlOptions=array('empty'=>'Select One', 'class'=>'g3',)); ?>
                            <span class="label p-p9">=</span><label class="goals-metric p-mr5"><?php echo $model->monthlyLeadGen;?></label><span class="label p-pt8">Hours per Month @ 4 lead gen days per week</span>
		        			<?php echo $form->error($model,'lead_gen_minutes_per_day'); ?>
		        		</td>
		        	</tr>
		        	<?php echo $form->hiddenField($model,'contact_id');?>
		        </table>
	    	</div>
		</div>
	</div>
	<?php $this->endStmPortletContent(); ?>
	<div id="submit-button-wrapper"><button type="submit" class="submit wide">Submit to Calculate Goal</button></div>
<?php $this->endWidget(); ?>

protected/modules/admin/views/goals/form.php
<?
$this->breadcrumbs=array(
	ucfirst($this->action->id) =>'',
);
// if ($mode == 'Edit')
// 	$this->breadcrumbs = CMap::mergeArray($this->breadcrumbs, array('Edit'=>'',));
// if ($mode == 'Add')
// 	$this->breadcrumbs = CMap::mergeArray($this->breadcrumbs, array('Add'=>'',));
?>
<div id="content-header">
	<h1 style="line-height: 1.2;"><?=$model->contact->fullName;?><br/><?php echo ucfirst($this->action->id)?> Goal :: <?php echo $model->name?></h1>
</div>

<?php echo $this->renderPartial('_form', array('model'=>$model,'mode'=>$mode,)); ?>

protected/modules/admin/views/goals/list.php
<?
$this->breadcrumbs=array(
	'List'=>''
);
    if(Yii::app()->user->checkAccess('owner')):
    Yii::app()->clientScript->registerScript('search', <<<JS
        $('#listview-search form').change(function() {
            $('#listview-search form').submit();
        });

        $('#listview-search form').submit(function() {
            $.fn.yiiGridView.update("goals-grid", {
                data: $(this).serialize()
            });
            return false;
        });
JS
    );
endif;
?>
<div id="listview-actions">
    <a href="/admin/goals/calculator" class="button gray icon i_stm_edit">Calculator</a>
	<a href="/admin/goals/add" class="button gray icon i_stm_add">Add New Goal</a>
    <a href="/admin/goals/oneThing" class="button gray icon i_stm_search">View One Thing</a>
    <a href="/admin/goals/addOneThing" class="button gray icon i_stm_add">Add One Thing</a>
</div>
<div id="content-header">
	<h1>Goals List</h1>
</div>

<?php if(Yii::app()->user->checkAccess('owner')): ?>
<div id="listview-search" class="g100 p-mh0 p-pv10 grey-gradient-box">
    <?php $form=$this->beginWidget('CActiveForm', array(
            'action'=>Yii::app()->createUrl($this->route),
            'method'=>'get',
            'id'=>'goals-list-search',
        )); ?>
    <div class="g4"></div>
    <div class="g3">
        <label class="g2">Agent:</label>
    <span class="g10"><?php
        echo $form->dropDownList($model,'contact_id', CHtml::listData(Contacts::model()->byActiveAdmins()->orderByName()->findAll(), 'id', 'fullName'), $htmlOptions=array('class'=>'g12'));
        $this->widget('admin_module.extensions.EChosen.EChosen', array('target' => '#Goals_contact_id')); ?></span>
    </div>
    <div class="g2 submit" style="text-align:center"><?php echo CHtml::submitButton('SEARCH', array('class'=>'button')); ?></div>
    <?php $this->endWidget(); ?>
</div>
<?endif;?>
<?php
$this->widget('admin_module.components.StmGridView', array(
	'id'=>'goals-grid',
	'dataProvider'=>$model->search(),
	'itemsCssClass'=>'datatables',
	'columns'=>array(
		array(
			'type'=>'raw',
			'name'=>'Status',
			'value'=>'StmFormHelper::getStatusBooleanName($data->status_ma)',
			),
        'contact.fullName',
		'name',
		'year',
		array(
			'type'=>'raw',
			'name'=>'Avg Sales Price',
			'value'=>'Yii::app()->format->formatDollars($data->average_sales_price)',
			),
		array(
			'type'=>'raw',
			'name'=>'Annual Closings',
			'value'=>'$data->annualClosings',
			),
		array(
			'type'=>'raw',
			'name'=>'Annual Income',
			'value'=>'Yii::app()->format->formatDollars($data->income_per_year)',
			),
		array(
			'type'=>'raw',
			'name'=>'',
			'value'=>'
				"<div><a href=\"/admin/goals/edit/".$data->id."\" class=\"button gray icon i_stm_edit grey-button\">Edit</a></div>"
			',
			'htmlOptions'=>array('style'=>'width:80px'),
		),
        array(
            'type'=>'raw',
            'name'=>'',
            'value'=>'($data->hasWeeklyGoals)? "<div><a href=\"/admin/goals/editWeekly/".$data->id."\" class=\"button gray icon i_stm_edit grey-button\">Edit Weekly Goals</a></div>" :
				"<div><a href=\"/admin/goals/addWeekly/".$data->id."\" class=\"button gray icon i_stm_add grey-button\">Add Weekly Goals</a></div>"
			',
            'htmlOptions'=>array('style'=>'width:160px'),
        ),
	),
));
?>